pipline {
    agent any
    

    stages {

        stage('Setup Python') {
            steps {              
                script {                   
                    sh 'python3 --version'  // Verifica que Python 3 está disponible en el sistema
                    sh "python3 -m venv venv" // Crea un entorno virtual
                }
            }
        }

        stage('Install Dependencies') {
            steps {               
                script {                  
                    sh '. venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }

        stage("build"){
            steps{               
                echo 'Realizando empaquetado...'             
                sh 'tar -czvf proyecto_python.tar.gz .'
            }
        }

        
    }


}