version: '3.8'

services:
  pedidos-api:
    build: ./pedidos_api
    ports:
      - "8000:8000"
    networks:
      - restaurant-net
    depends_on:
      - inventario-api

  inventario-api:
    build: ./inventario_api
    ports:
      - "8001:8001"
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
