name: CI/CD
on:
  workflow_dispatch:
    inputs:
      Execute-Unit-Test:
        description: "Execute Unit Test?"
        type: boolean
        default: false
        required: true

jobs:
  set-workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ''
          persist-credentials: false
          path: ./project
      - name: Check-files
        run: |
          ls -la project/
      - name: Execute Unit Test (inventario api)
        run: |
          export PYTHONPATH="/home/runner/work/Microservices/Microservices/project"
          cd project/inventario_api
          pip3 install -r requirements.txt
          cd ..
          pytest inventario_api/tests/test_app.py      